import { AppDataSource } from "../dataSource";
import { CentrosEstudio } from "../entities/CentrosEstudio";

export async function runCentrosEstudioSeeder()
{
    const model = AppDataSource.getRepository(CentrosEstudio);

    // Como se extrajeron los datos:
    //
    // UNIVERSIDADES: https://www.sunedu.gob.pe/lista-universidades/
    // jQuery(".column-2").each(function()
    // {
    //     let nombre = jQuery(this).text();
    //     if(nombre.includes('Universidad') && !nombre.includes('Denominación'))
    //         console.log(jQuery(this).text().replace(/\([^)]*\)/g, '').trim())
    // });
    //
    // INSTITUTOS: https://es.wikipedia.org/wiki/Anexo:Institutos_profesionales_y_centros_de_formaci%C3%B3n_t%C3%A9cnica_del_Per%C3%BA
    // document.querySelectorAll("tbody td[style]").forEach(function(item, i) {
    //     console.log(item.innerText);
    // });

    const dataToSeed = [
        {nombre: "Universidad Nacional Mayor de San Marcos", tipoCeId: 4},
        {nombre: "Universidad Nacional de San Cristóbal de Huamanga", tipoCeId: 4},
        {nombre: "Universidad Nacional de San Antonio Abad del Cusco", tipoCeId: 4},
        {nombre: "Universidad Nacional de Trujillo", tipoCeId: 4},
        {nombre: "Universidad Nacional de San Agustín de Arequipa", tipoCeId: 4},
        {nombre: "Universidad Nacional de Ingeniería", tipoCeId: 4},
        {nombre: "Universidad Nacional Agraria La Molina", tipoCeId: 4},
        {nombre: "Universidad Nacional San Luis Gonzaga", tipoCeId: 4},
        {nombre: "Universidad Nacional del Centro del Perú", tipoCeId: 4},
        {nombre: "Universidad Nacional de la Amazonía Peruana", tipoCeId: 4},
        {nombre: "Universidad Nacional del Altiplano", tipoCeId: 4},
        {nombre: "Universidad Nacional de Piura", tipoCeId: 4},
        {nombre: "Universidad Nacional de Cajamarca", tipoCeId: 4},
        {nombre: "Universidad Nacional Federico Villarreal", tipoCeId: 4},
        {nombre: "Universidad Nacional Agraria de la Selva", tipoCeId: 4},
        {nombre: "Universidad Nacional Hermilio Valdizán de Huánuco", tipoCeId: 4},
        {nombre: "Universidad Nacional de Educación Enrique Guzmán y Valle", tipoCeId: 4},
        {nombre: "Universidad Nacional Daniel Alcides Carrión", tipoCeId: 4},
        {nombre: "Universidad Nacional del Callao", tipoCeId: 4},
        {nombre: "Universidad Nacional José Faustino Sánchez Carrión", tipoCeId: 4},
        {nombre: "Universidad Nacional Pedro Ruiz Gallo", tipoCeId: 4},
        {nombre: "Universidad Nacional Jorge Basadre Grohmann", tipoCeId: 4},
        {nombre: "Universidad Nacional Santiago Antúnez de Mayolo", tipoCeId: 4},
        {nombre: "Universidad Nacional de San Martín", tipoCeId: 4},
        {nombre: "Universidad Nacional de Ucayali", tipoCeId: 4},
        {nombre: "Universidad Nacional de Tumbes", tipoCeId: 4},
        {nombre: "Universidad Nacional del Santa", tipoCeId: 4},
        {nombre: "Universidad Nacional de Huancavelica", tipoCeId: 4},
        {nombre: "Universidad Nacional Amazónica de Madre de Dios", tipoCeId: 4},
        {nombre: "Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas", tipoCeId: 4},
        {nombre: "Universidad Nacional Micaela Bastidas de Apurímac", tipoCeId: 4},
        {nombre: "Universidad Nacional Intercultural de la Amazonía", tipoCeId: 4},
        {nombre: "Universidad Nacional Tecnológica de Lima Sur", tipoCeId: 4},
        {nombre: "Universidad Nacional José María Arguedas", tipoCeId: 4},
        {nombre: "Universidad Nacional de Moquegua", tipoCeId: 4},
        {nombre: "Universidad Nacional de Juliaca", tipoCeId: 4},
        {nombre: "Universidad Nacional de Jaén", tipoCeId: 4},
        {nombre: "Universidad Nacional de Frontera", tipoCeId: 4},
        {nombre: "Universidad Nacional Autónoma de Chota", tipoCeId: 4},
        {nombre: "Universidad Nacional de Barranca", tipoCeId: 4},
        {nombre: "Universidad Nacional de Cañete", tipoCeId: 4},
        {nombre: "Universidad Nacional Intercultural Fabiola Salazar Leguía de Bagua", tipoCeId: 4},
        {nombre: "Universidad Nacional Intercultural de la Selva Central Juan Santos Atahualpa", tipoCeId: 4},
        {nombre: "Universidad Nacional Intercultural de Quillabamba", tipoCeId: 4},
        {nombre: "Universidad Nacional Autónoma de Alto Amazonas", tipoCeId: 4},
        {nombre: "Universidad Nacional Autónoma Altoandina de Tarma", tipoCeId: 4},
        {nombre: "Universidad Nacional Autónoma de Huanta", tipoCeId: 4},
        {nombre: "Universidad Nacional Tecnológica de San Juan de Lurigancho", tipoCeId: 4},
        {nombre: "Universidad Nacional Autónoma de Tayacaja Daniel Hernández Morillo", tipoCeId: 4},
        {nombre: "Universidad Nacional Ciro Alegría", tipoCeId: 4},
        {nombre: "Pontificia Universidad Católica del Perú", tipoCeId: 4},
        {nombre: "Universidad Peruana Cayetano Heredia", tipoCeId: 4},
        {nombre: "Universidad Católica de Santa María", tipoCeId: 4},
        {nombre: "Universidad del Pacífico", tipoCeId: 4},
        {nombre: "Universidad de Lima", tipoCeId: 4},
        {nombre: "Universidad de San Martín de Porres", tipoCeId: 4},
        {nombre: "Universidad Femenina del Sagrado Corazón", tipoCeId: 4},
        {nombre: "Universidad Inca Garcilaso de la Vega", tipoCeId: 4},
        {nombre: "Universidad de Piura", tipoCeId: 4},
        {nombre: "Universidad Ricardo Palma", tipoCeId: 4},
        {nombre: "Universidad Andina Néstor Cáceres Velásquez", tipoCeId: 4},
        {nombre: "Universidad Peruana Los Andes", tipoCeId: 4},
        {nombre: "Universidad Peruana Unión", tipoCeId: 4},
        {nombre: "Universidad Andina del Cusco", tipoCeId: 4},
        {nombre: "Universidad Tecnológica de los Andes", tipoCeId: 4},
        {nombre: "Universidad Privada de Tacna", tipoCeId: 4},
        {nombre: "Universidad Particular de Chiclayo", tipoCeId: 4},
        {nombre: "Universidad San Pedro", tipoCeId: 4},
        {nombre: "Universidad Privada Antenor Orrego", tipoCeId: 4},
        {nombre: "Universidad de Huánuco", tipoCeId: 4},
        {nombre: "Universidad José Carlos Mariátegui", tipoCeId: 4},
        {nombre: "Universidad Marcelino Champagnat", tipoCeId: 4},
        {nombre: "Universidad Científica del Perú", tipoCeId: 4},
        {nombre: "Universidad César Vallejo S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Católica Los Ángeles de Chimbote", tipoCeId: 4},
        {nombre: "Universidad Peruana de Ciencias Aplicadas S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Privada del Norte S.A.C.", tipoCeId: 4},
        {nombre: "Universidad San Ignacio de Loyola  S.A.", tipoCeId: 4},
        {nombre: "Universidad Alas Peruanas", tipoCeId: 4},
        {nombre: "Universidad Privada Norbert Wiener", tipoCeId: 4},
        {nombre: "Universidad Católica San Pablo", tipoCeId: 4},
        {nombre: "Grupo Educativo Universidad Privada de Ica S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Privada San Juan Bautista S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Tecnológica del Perú", tipoCeId: 4},
        {nombre: "Universidad Continental S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Científica del Sur S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Católica Santo Toribio de Mogrovejo", tipoCeId: 4},
        {nombre: "Universidad Privada Antonio Guillermo Urrelo", tipoCeId: 4},
        {nombre: "Universidad Católica Sedes Sapientiae", tipoCeId: 4},
        {nombre: "Universidad Señor de Sipán", tipoCeId: 4},
        {nombre: "Universidad Católica de Trujillo Benedicto XVI", tipoCeId: 4},
        {nombre: "Universidad Peruana de las Américas", tipoCeId: 4},
        {nombre: "Universidad ESAN", tipoCeId: 4},
        {nombre: "Universidad Antonio Ruiz de Montoya", tipoCeId: 4},
        {nombre: "Universidad Peruana de Ciencias e Informática", tipoCeId: 4},
        {nombre: "Universidad para el Desarrollo Andino", tipoCeId: 4},
        {nombre: "Universidad Privada Telesup", tipoCeId: 4},
        {nombre: "Universidad Sergio Bernales S.A.", tipoCeId: 4},
        {nombre: "Universidad Privada de Pucallpa S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Autónoma de Ica S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Privada de Trujillo", tipoCeId: 4},
        {nombre: "Universidad Privada San Carlos", tipoCeId: 4},
        {nombre: "Universidad Peruana Simón Bolivar", tipoCeId: 4},
        {nombre: "Universidad Peruana de Integración Global S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Peruana del Oriente S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Autónoma del Perú", tipoCeId: 4},
        {nombre: "Universidad de Ciencias y Humanidades", tipoCeId: 4},
        {nombre: "Universidad Privada Juan Mejía Baca", tipoCeId: 4},
        {nombre: "Universidad Jaime Bausate y Meza", tipoCeId: 4},
        {nombre: "Universidad Peruana del Centro", tipoCeId: 4},
        {nombre: "Universidad Privada Arzobispo Loayza S.A.C", tipoCeId: 4},
        {nombre: "Universidad Le Cordon Bleu S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Privada de Huancayo Franklin Roosevelt", tipoCeId: 4},
        {nombre: "Universidad de Lambayeque S.A.C.", tipoCeId: 4},
        {nombre: "Universidad de Ciencias y Artes de América Latina S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Peruana de Arte Orval S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Privada de la Selva Peruana", tipoCeId: 4},
        {nombre: "Universidad Ciencias de la Salud", tipoCeId: 4},
        {nombre: "Universidad de Ayacucho Federico Froebel", tipoCeId: 4},
        {nombre: "Universidad Peruana de Investigación y Negocios S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Peruana Austral del Cusco", tipoCeId: 4},
        {nombre: "Universidad Autónoma San Francisco", tipoCeId: 4},
        {nombre: "Universidad San Andrés", tipoCeId: 4},
        {nombre: "Universidad Interamericana para el Desarrollo", tipoCeId: 4},
        {nombre: "Universidad Privada Juan Pablo II", tipoCeId: 4},
        {nombre: "Universidad Privada Leonardo Da Vinci S.A.C.", tipoCeId: 4},
        {nombre: "Universidad de Ingeniería y Tecnología", tipoCeId: 4},
        {nombre: "Universidad La Salle", tipoCeId: 4},
        {nombre: "Universidad Latinoamericana CIMA", tipoCeId: 4},
        {nombre: "Universidad Privada Autónoma del Sur", tipoCeId: 4},
        {nombre: "Universidad María Auxiliadora", tipoCeId: 4},
        {nombre: "Universidad Politécnica Amazónica S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Santo Domingo de Guzmán", tipoCeId: 4},
        {nombre: "Universidad Marítima del Perú", tipoCeId: 4},
        {nombre: "Universidad Privada Líder Peruana", tipoCeId: 4},
        {nombre: "Universidad Privada Peruano Alemana S.A.C.", tipoCeId: 4},
        {nombre: "Universidad Global del Cusco", tipoCeId: 4},
        {nombre: "Universidad Santo Tomás de Aquino de Ciencia e Integración", tipoCeId: 4},
        {nombre: "Universidad Privada SISE", tipoCeId: 4},
        {nombre: "Universidad Seminario Evangélico de Lima", tipoCeId: 4},
        {nombre: "Universidad Seminario Bíblico Andino", tipoCeId: 4},
        {nombre: "Universidad Católica San José", tipoCeId: 4},
        {nombre: "IESTP José Pardo", tipoCeId: 3},
        {nombre: "IESPP José María Arguedas de Andahuaylas", tipoCeId: 3},
        {nombre: "Escuela Nacional de Artes Gráficas CETPRO-PROMAE", tipoCeId: 3},
        {nombre: "IESPP Piura", tipoCeId: 3},
        {nombre: "IESTP Argentina", tipoCeId: 3},
        {nombre: "ISPP Puno", tipoCeId: 3},
        {nombre: "IESPP Pomabamba", tipoCeId: 3},
        {nombre: "IESTP Diseño y Comunicación, IDC", tipoCeId: 3},
        {nombre: "IESTP Recuay", tipoCeId: 3},
        {nombre: "IESTP Pedro P. Ruíz", tipoCeId: 3},
        {nombre: "IESTP María Rosario Araoz Pinto", tipoCeId: 3},
        {nombre: "IESTP PNP Gral. GC. Oscar Arteta Terzi", tipoCeId: 3},
        {nombre: "IESPP Gamaniel Blanco Murillo", tipoCeId: 3},
        {nombre: "IESPP Monseñor Elías Olázar", tipoCeId: 3},
        {nombre: "IESTP Manuel Nuñez Butrón", tipoCeId: 3},
        {nombre: "IESTP Pasco", tipoCeId: 3},
        {nombre: "IESTP República Federal de Alemania, ISTRFA", tipoCeId: 3},
        {nombre: "IESPP Chimbote", tipoCeId: 3},
        {nombre: "IESTP Francisco de Paula Gonzales Vigil, Tecnológico Vigil", tipoCeId: 3},
        {nombre: "IESTP Huancavelica", tipoCeId: 3},
        {nombre: "IESTP Manuel Arevalo Cáceres", tipoCeId: 3},
        {nombre: "IESTP La Unión", tipoCeId: 3},
        {nombre: "IESTP Naranjillo", tipoCeId: 3},
        {nombre: "IESTP Luis E. Varcacel", tipoCeId: 3},
        {nombre: "IESPP María Madre", tipoCeId: 3},
        {nombre: "IESTP Reyna de las Américas", tipoCeId: 3},
        {nombre: "IESTP 24 de Julio", tipoCeId: 3},
        {nombre: "IESTP Misioneros Monfortianos", tipoCeId: 3},
        {nombre: "IESTP Centro de Formación Agrícola Moquegua, CFAM", tipoCeId: 3},
        {nombre: "IESTP Antenor Orrego Espinoza", tipoCeId: 3},
        {nombre: "IESTP San Pedro del Valle de Mala", tipoCeId: 3},
        {nombre: "IESTP Carlos Cueto Fernandini", tipoCeId: 3},
        {nombre: "IESTP Oxapampa", tipoCeId: 3},
        {nombre: "IESPP Alianza Ichuña Bélgica", tipoCeId: 3},
        {nombre: "CETPRO Almirante Miguel Grau", tipoCeId: 3},
        {nombre: "IESTP Virgen de Guadalupe", tipoCeId: 3},
        {nombre: "IESTP Mario Gutiérrez López", tipoCeId: 3},
        {nombre: "ITAE - Instituto Técnico de Administración de Empresas", tipoCeId: 3},
        {nombre: "IESTP Gran Chavín Huaraz", tipoCeId: 3},
        {nombre: "IESTP CEPEA", tipoCeId: 3},
        {nombre: "IDAT", tipoCeId: 3},
        {nombre: "CIBERTEC", tipoCeId: 3},
        {nombre: "Instituto Superior SISE", tipoCeId: 3},
        {nombre: "Columbia Centro de Estudios", tipoCeId: 3},
        {nombre: "CIMAS", tipoCeId: 3},
        {nombre: "IPM Instituto Peruano de Marketing", tipoCeId: 3},
        {nombre: "AVIA Centro de Estudios de Aviación Profesional", tipoCeId: 3},
        {nombre: "ISTP Amauta", tipoCeId: 3},
        {nombre: "IESTP Paul Müller", tipoCeId: 3},
        {nombre: "Instituto Superior Norbert Wiener", tipoCeId: 3},
        {nombre: "IPAD Instituto Peruano de Arte y Diseño", tipoCeId: 3},
        {nombre: "IESTP de Diseño Publicidad Leo Design", tipoCeId: 3},
        {nombre: "IST Santa Rosa", tipoCeId: 3},
        {nombre: "CECITEL Centro de Capacitación e Investigación en Telecomunicaciones", tipoCeId: 3},
        {nombre: "IESTP Perú Pacífico", tipoCeId: 3},
        {nombre: "IFB - CERTUS", tipoCeId: 3},
        {nombre: "Modabell Instituto Superior Selene", tipoCeId: 3},
        {nombre: "MAD Escuela de Moda", tipoCeId: 3},
        {nombre: "IESTP Centro de la Imagen", tipoCeId: 3},
        {nombre: "ISTP SECOMTUR", tipoCeId: 3},
        {nombre: "IESTP IDATUR", tipoCeId: 3},
        {nombre: "Instituto Superior AVANSYS", tipoCeId: 3},
        {nombre: "Instituto Superior CESCA", tipoCeId: 3}
    ];

    for (const data of dataToSeed)
    {
        try {
            const centroEstudio = model.create(data);
            await model.save(centroEstudio);
        }
        catch(error){
            console.log('CentrosEstudio | El registro ya existe: '+JSON.stringify(data));
        }
    }

    console.log('Seeder para CentrosEstudio completado.');
}